name: Build TetherFi APK (Gradle 8.14)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle 8.14
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'  

      - name: Write verification metadata
        run: ./gradlew --write-verification-metadata sha256,pgp clean

      - name: Build Google APK
        run: ./gradlew app:assembleGoogle -U

      - name: Upload Google APK
        uses: actions/upload-artifact@v4
        with:
          name: tetherfi-google-apk
          path: app/build/outputs/apk/google/app-google.apk
      - name: Send build folder to NTFY server
        run: |
          tar -czf build.tar.gz app/build
          curl -X POST -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -H "Title: Build Folder" \
            -H "Tags: build,upload" \
            -F "file=@build.tar.gz" \
            ${{ secrets.NTFY_URL }}