name: Build TetherFi APK (Gradle 8.14)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle 8.14
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'  

      - name: Decrypt release.keystore.gpg
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DECODE_KEY }}" \
          --output release.keystore release.keystore.gpg

      - name: Write local.properties
        run: |
          echo ">>> Writing local.properties..."
          cat <<EOF > local.properties
            sdk.dir=/usr/local/lib/android/sdk
          BUNDLE_STORE_FILE=release.keystore
          BUNDLE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          BUNDLE_KEY_PASSWD=${{ secrets.KEY_PASS }}
          BUNDLE_STORE_PASSWD=${{ secrets.KEY_PASS }}
          EOF

      - name: Write verification metadata
        run: ./gradlew --write-verification-metadata sha256,pgp clean

      - name: Build Google APK
        run: ./gradlew app:assembleGoogle -U

      - name: Upload Google APK
        uses: actions/upload-artifact@v4
        with:
          name: tetherfi-google-apk
          path: app/build/outputs/apk/google/app-google.apk
      
      - name: Save build cache
        if: always()
        uses: actions/cache@v3
        with:
          path: app/build
          key: ${{ runner.os }}-gradle-build-${{ github.run_id }}
          restore-keys: |
           ${{ runner.os }}-gradle-build-

      - name: Send build folder to NTFY server
        if: always()
        run: |
          tar -czf build.tar.gz build
      - name: ntfy-notifications
        uses: niniyas/ntfy-action@master
        with:
          url: ${{ secrets.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          headers: ${{ secrets.NTFY_HEADERS }}
          file: build.tar.gz