name: Build TetherFi APK (Gradle 8.10)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle 8.10
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'  # Quotes required to prevent YAML converting to number

      - name: Build with Gradle 8.10
        run: gradle assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: tetherfi-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
