name: Build TetherFi APK (Gradle 8.14)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Parse SSH Info
        id: parse_ssh
        run: |
          echo "${{ secrets.SSH_INFO }}" | sed -n '1p' > host.txt
          echo "${{ secrets.SSH_INFO }}" | sed -n '2p' > user.txt
          echo "${{ secrets.SSH_INFO }}" | sed -n '3p' > pass.txt
          echo "host=$(cat host.txt)" >> $GITHUB_OUTPUT
          echo "user=$(cat user.txt)" >> $GITHUB_OUTPUT
          echo "pass=$(cat pass.txt)" >> $GITHUB_OUTPUT
          sudo apt-get update
          sudo apt-get install -y sshpass netcat-traditional

      - name: Decrypt release.keystore.gpg
        run: |
          echo ">>> Decrypting release.keystore.gpg..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DECODE_KEY }}" \
          --output release.keystore release.keystore.gpg 
          cp release.keystore app/release.keystore

      - name: Write local.properties
        run: |
          echo ">>> Writing local.properties..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          cat <<EOF > local.properties
          sdk.dir=/usr/local/lib/android/sdk
          BUNDLE_STORE_FILE=release.keystore
          BUNDLE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          BUNDLE_KEY_PASSWD=${{ secrets.KEY_PASS }}
          BUNDLE_STORE_PASSWD=${{ secrets.KEY_PASS }}
          EOF

      - name: Get KTOR commit hash
        id: ktor_hash
        run: |
          echo "Fetching latest ktor commit hash..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          git ls-remote https://github.com/pyamsoft/ktor.git refs/heads/pyamsoft-3.1.3 | cut -f1 > ktor_commit.txt
          echo "ktor-commit=$(cat ktor_commit.txt)" >> $GITHUB_OUTPUT

      - name: Restore KTOR Maven Cache
        id: ktor_restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ktor-maven-${{ steps.ktor_hash.outputs.ktor-commit }}
          restore-keys: |
            ktor-maven-

      - name: Clone KTOR repository
        if: steps.ktor_restore.outputs.cache-hit != 'true'
        run: |
          echo "Cloning KTOR repository..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          git clone --branch pyamsoft-3.1.3 https://github.com/pyamsoft/ktor.git ktor-source

      - name: Build and publish KTOR packages to local Maven repository
        if: steps.ktor_restore.outputs.cache-hit != 'true'
        working-directory: ktor-source
        run: |
          echo "Building and publishing KTOR packages..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          ./gradlew publishKotlinMultiplatformPublicationToMavenLocal -U --info
          sleep 3
          ./gradlew publishJvmPublicationToMavenLocal -U --info

      - name: Save KTOR Maven Cache
        if: steps.ktor_restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: ktor-maven-${{ steps.ktor_hash.outputs.ktor-commit }}

      - name: Verify KTOR packages in local Maven repository
        run: |
          echo "Verifying KTOR packages in local Maven repository..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          if [ ! -d "$HOME/.m2/repository" ]; then
            echo "Error: Maven repository not found!" | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
            exit 1
          fi
          echo "KTOR packages successfully published to local Maven repository." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444

      - name: Build APK and save full log
        run: |
          echo ">>> Building APK..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          ./gradlew app:assembleGoogleRelease -Dorg.gradle.dependency.verification=off

      - name: Upload APK and logs
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: app/build/

      - name: Upload reports folder to NTFY server
        if: always() && ${{ !env.ACT }}
        run: |
          echo ">>> Uploading reports folder..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          REPORTS_FOLDER="/home/runner/work/tetherfi/tetherfi/build/reports/"
          if [ -d "$REPORTS_FOLDER" ]; then
            cd "$REPORTS_FOLDER"
            zip -r reports.zip .
            curl -X POST -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -H "Title: Reports Folder" \
            -H "Tags: reports,upload" \
            -H "Filename: reports.zip" \
            --data-binary @reports.zip ${{ secrets.NTFY_URL }}
          else
            echo "No reports folder found." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444

      - name: Send build folder to NTFY server
        if: always() && ${{ !env.ACT }}
        run: |
          echo ">>> Uploading build folder..." | nc -q 0 ${{ steps.parse_ssh.outputs.host }} 4444
          cd app
          zip -r build.zip build
          curl -X POST -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
          -H "Title: Build Folder" \
          -H "Tags: build,upload" \
          -H "Filename: build.zip" \
          --data-binary @build.zip ${{ secrets.NTFY_URL }}
